[package]
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
name = "logslash"
version = "0.1.0"

[dependencies]
assert_matches = "1.0.1"
error-chain = "0.7.1"
futures = "0.1.6"
nom = "2.0.0"
tokio-core = "0.1.1"
